### ISSUE TITLE
Need a script to create a list of added cards by set since a commit ID

### ISSUE THREAD

**Issue by LevelX2** [magefree/xmage-maintenance#1]
Until the reorg of the set lins I used this command to get a list of the added ccards with set:

git log a6747590b336329404d34f3b1780b5fe9aab7340..head --diff-filter=A --name-status | sed -ne "s/^A[^u]Mage.Sets\/src\/mage\/sets\///p" | sort > added_cards.txt

I changed it to this, but that does only create a list of card classes.
git log b2bd7f5e24db9a1e5c07c64e66583ec183bb5bd8..head --diff-filter=A --name-status | sed -ne "s/^A[^u]Mage.Sets\/src\/mage\/cards\///p" | sort > added_cards.txt

Anyone any idea how to change that, to get that list with the new structure?
Or if one could create a script to get that information for a new release would be perfect.

**Comment by fenhl** [comment]
Should be doable by iterating over the entire MTG JSON database and calling `implemented` on every card using the latest release, then repeating for the current master, and diffing the results.
